name: Update Aragon names
on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 5:42 UTC
    - cron: "42 5 * * 1"
jobs:
  update_names:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: aragon-names
    - name: Run Script
      run: python ./updateAragonNames.py > ./cache_scripts/aragon/dao_names.json
    - name: Commit files
      run: |
        git add ./cache_scripts/aragon_dao_names.json
        git commit -m "Updated Aragon DAO Names `date -I`"
    - name: Push Changes
      uses: peter-evans/create-pull-request@v3
      with:
        title: New Aragon Names
        reviewers: daviddavo
        labels: automated
        base: develop
